keys:
- &cypurs age17ey43hew3rhct2s08duwvkarnqcqu58gaat947u0ecxtj4nuf36qpc2k2e
- &manhattan age12gdm5t5d7q2h8ysmn3r2f9hj6cwj9rzc8y9syguf2yp8s9272ggq6jgyd9
- &costarica age1jh7ggpp3qx0p35en6vsqyna8fz4j5lwap5p8u63qx5xp97uax3hqsn522x
creation_rules:
- path_regex: "secrets/.*\\.(yaml|json|env|ini)$"
  # 冷知识普及时间，yml 这种后现代缩写主要是为了兼容某个最长只能有三位扩展名的老登系统。
  # 所以，未来只会考虑 yaml 扩展名。
  key_groups:
  - age:
    - *cypurs
    - *manhattan
    - *costarica
