name: 严格格式检查

on:
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  nixfmt:
    name: nix fmt 检查
    runs-on: codeberg-medium-lazy

    steps:
      - name: 拉取仓库
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          ref: ${{ forgejo.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: 恢复 Nix 缓存
        uses: https://data.forgejo.org/actions/cache@v5
        with:
          path: |
            ~/.cache/nix
            ~/.local/state/nix
          key: nix-user-cache-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-user-cache-${{ runner.os }}-

      - name: 安装 Lix
        shell: bash
        run: |
          set -euo pipefail
          curl --proto '=https' --tlsv1.2 -fsSL https://install.lix.systems/lix | bash -s -- install linux \
            --extra-conf "sandbox = false" \
            --init none \
            --no-confirm

          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

          mkdir -p "$HOME/.config/nix"

          cat > "$HOME/.config/nix/nix.conf" <<'EOF'
          experimental-features = nix-command flakes
          extra-substituters = https://nix.mcseekeri.com?priority=51 
          extra-trusted-public-keys = nix.mcseekeri.com-1:3gd0/2u7IOF7YooxEiBbWTvRCYGC53S2UoqFdnCUYHc=
          EOF

      - name: 执行 treefmt 检查
        shell: bash
        run: |
          set -euo pipefail
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix build .#checks.x86_64-linux.treefmt --accept-flake-config
