cloudflared-creds: ENC[AES256_GCM,data:Kmfdd4f6HQll7GnxMpmkRRC4haj7G8TVB3tAGNG4TR6Czs+cXLeWyh9w2Uu77wcXz2pi877bhjVbstzvfQte4eYRhgjWkW366RBBda1yERVw8t2ziClD0SzIfDV6zm+RKeh+0pKg3bysc7hhj4jbYiAEVdEmrKdXvljI2rkfnIpBbZdFDY4jo8E4i60KJKEAwgqqwaMwOcNn6Ebe/Ly4oj4=,iv:hibF5C2Nkd9UZvSpsNswJEnfhwpZa98jzeDDj1e1LRU=,tag:ZuUmJJK5ApwWIPorkYTnqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjfem9kpmexdtucmxvzvhvt9uz4wk29q6l3ap0sv4tvg49mhj4espup3wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb2VhRjhXRys4VGhZMDhS
            MXJKY2c0VG82eUI0QUxLbVJQcjZJdmkwTFZ3CkxVSkZ5eUlBVEZlYmhCNFcrZUZx
            WlNvWDhLT045TVI3TVlQNWJmQW5yMW8KLS0tIDNIZmtlVkY0cENFR1Zndmp5NzVi
            b2t1YVRUL1pyVXNqaXRKelpWVWJ2OWcKV45+KYJ369ZNY+Ar8wG7IUjTdmsR5PLA
            lvC4c7Kh/iZToKTyJ2Jg8iqClxUpUb0pr8r5PaY24K1yCkaBnbuihw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arems4jk0dwzgd09xm9xejmvd6ttyd6jf89qqugqnzz8quxwup8s6p0pgf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MURkVGFrb2tQMmdpRWpC
            ZDUyYVZheC81TkNGbmIrSVV2NCtrbGNVbmpBClEreWd0S3NVZ3huQXNDbGVxNDE2
            ZG1xRlhhVVo1RkJNWDFCTVBmWjBWbWsKLS0tIHEwakZBVHZJRmdsL1hnazZHOWVH
            RC82RUtpeUxYOStuMXdSRmFJR1grUEUKBbEcAT45k6tURPDmPZh6Ra7vg6oxH/jz
            GfohQbEMvRqK9wjv90cEn4BOmOxYeSjYC5cVWwMsjnXDCGzhpV//yA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k2apmcsa5hhpfrp89dedafp9gdxk5hac4s3vufu8khzmrf0msugse089vx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVFpLTkYrU2JEVXN2L0FG
            ZFJSZVg5b29URG5aSnVoOWV2a1dMSy8xTzBvCk9iSTJNSXVrbXVtekFQZlVlbDBN
            bGR3YTZJRncxSWRFS1ZWN0JXRGRaK1EKLS0tIEtVUitxcHhjRlJDSGtjZyt6dUYw
            U2pHaTVodlpBUnZVczUrQyt3UmRpZjQKgiUGrQCgW/DusUHuZSMUc4ppbg0uOZMY
            bUkT2/dDQfrtEDgpIDwOaMmPxXrya4yR+owu7W53yUJOkoHAsMeN7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T12:14:47Z"
    mac: ENC[AES256_GCM,data:TKOMiYZHZwx8e5cIeQWDC62c8vVzPSQfP6/0mGDBDWGjaurDNTH/O8/PuLRd6j32oJoxhpMf7Ddfd0KZN8nezSgIB8zfy2PQpTNHyaTDRuMt4VpfSuDakEF3Z/xZIwWcaAKu0p2YJAH8GCWDO4L0HU//Op1pszgOBgrTvi1h5rc=,iv:tHeFpqOfJo0ShdlgzWps5CSMy9weReFLt//yGhRvGqg=,tag:QtLIo9c8svk2dYipIOg0eA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
